blockExoticSubdeps: true
strictDepBuilds: true
saveExact: true

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - sharp
  - workerd

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - lefthook
