
# See https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "nihalgonsalves-com"
compatibility_date = "2024-05-05"
compatibility_flags = [ "nodejs_als" ]
main = "./dist/worker/serve-cloudflare.js"

routes = [
  { pattern = "nihalgonsalv.es", custom_domain = true },
]

[assets]
directory = "./dist/assets"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
# "single-page-application" | "404-page" | "none"
not_found_handling = "404-page"

