
# See https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "nihalgonsalves"
compatibility_date = "2024-09-02"
compatibility_flags = [ "nodejs_als" ]
pages_build_output_dir = "./dist"
